### PR TITLE
Fix for Angular version 4.0.0

### PR DESCRIPTION
**Pull request by ferdiemmen**
Hi,

I've forked your repository and fixed it so it works again with Angular 4.0.0.
Please, let me hear what you think of the changes and if you're going to pull this into your repo.

Kind regards

### CODE REVIEW

**Comment by subatomicglue** [comment]
Related:
I am getting this error with angular2-mediumeditor 1.0.6 and latest angular-cli which includes angular 4.0.0

```
ERROR in ./~/angular2-medium-editor/medium-editor.directive.ts
Module not found: Error: Can't resolve '@angular/forms/src/directives/shared' in '/Users/kevinmeinert/src/Platform/front/node_modules/angular2-medium-editor'
 @ ./~/angular2-medium-editor/medium-editor.directive.ts 11:0-73
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
```

This is currently blocking us from upgrading to angular4, which we need to fix other unrelated issues.

**Comment by subatomicglue** [comment]
TESTED...

I just patched this into my Angular4.0.0   `@angular/cli` `1.2.7` project, and it works well.  
Could we merge this in please?

@ferdiemmen Will this be backwards compatible with older 2.x angular   (angular-cli 1.0.0-beta and beyond)?

**Comment by ferdiemmen** [comment]
@subatomicglue I haven't tested it. Is this something we should look into before merging?

**Comment by subatomicglue** [comment]
I am not sure.  Was trying to think of all the reasons the maintainer might
reject this.  To get us ready for smooth acceptance ;-)...   but perhaps
this would be submitted to npm as a different version with different
dependencies.   I don't exactly know how it works with npm

**Comment by ferdiemmen** [comment]
Me neither. And the maintainer hasn't responded back to us for a month. I've decided to use my fork in the project I'm currently working on until this is merged. Thank you @subatomicglue for your help.

**Comment by subatomicglue** [comment]
I have also made a copy of your fork into my team's project repo as well.   Once this PR gets merged in, I'll switch back to `npm`, but for now we are good.

real question - should this be a new `npm` package i.e.  `angular4-medium-editor`  or should the npm package become something generically named like `ng2-medium-editor` with proper dependency versioning...   I'm sure the maintainer knows more about `npm` release procedure than I do :)

**Comment by subatomicglue** [comment]
To make this easy...    I added the following to my `package.json`:

```
"hack": "bash -c \"[[ ! -d '__angular4-medium-editor' ]] && echo '---\nPatching Medium Editor for Angular4 compatibility!\n---' && rm -rf __angular4-medium-editor && git clone git@github.com:ferdiemmen/angular2-medium-editor.git __angular4-medium-editor\"; cp __angular4-medium-editor/* node_modules/angular2-medium-editor/; exit 0",
```

Then run `npm run hack` before any step (like start).

```
"start": "npm run hack && node_modules/.bin/ng serve --port 4200",
"hack": "bash -c \"[[ ! -d '__angular4-medium-editor' ]] && echo '---\nPatching Medium Editor for Angular4 compatibility!\n---' && rm -rf __angular4-medium-editor && git clone git@github.com:ferdiemmen/angular2-medium-editor.git __angular4-medium-editor\"; cp __angular4-medium-editor/* node_modules/angular2-medium-editor/; exit 0",
```

Of course, I checked `__angular4-medium-editor` into our git, in case it ever goes away from `ferdiemmen`'s repo. :)

Hopefully this gets merged into the `angular2-medium-editor` npm repo so I can remove this weird hack.

**Comment by subatomicglue** [comment]
Alternate approach is to take on maintenance yourself, and simply copy [`medium-editor.directive.ts`](https://github.com/ferdiemmen/angular2-medium-editor/blob/master/medium-editor.directive.ts) from [ferdiemmen's fork](https://github.com/ferdiemmen/angular2-medium-editor) into your own project, and include with

```
import { MediumEditorDirective } from '<path-to>/medium-editor.directive';
```

Thinking I will be doing this...

**Comment by codiak** [comment]
Wow, I feel terrible for neglecting this. I'm so sorry, I've updated my Github notifications, and I've added you, ferdiemmen, as a collaborator. Thank you so much for figuring this out! I'll review with a pre-Angular 4 version today.

**Comment by ferdiemmen** [comment]
@codiak Thank you for getting back with us and making me collaborator.

**Comment by simison** [comment]
Hey all! @codiak @ferdiemmen what do you think about arranging a PR for Angular2+ into [original repo](https://github.com/thijsw/angular-medium-editor)? I think it would have more solid ground there and I assume @thijsw wouldn't mind to include you as maintainers as well.

**Comment by thijsw** [comment]
I am happy to accept these changes (and this v2 fork) as a PR into the original repository.

Echoing @simison message, I think it is indeed a good idea to have a single repository for this plugin that contains releases for both AngularJS 1.x and the newer Angular 2.x-5.x versions. I think npm is able to figure out which versions a project requires based on the Angular version used.

Of course I'd make @ferdiemmen and @codiak collaborators, especially since I'm not that experienced with Angular 2+ myself.

**Pull request merged**
