### PR TITLE
Use require to pull in MediumEditor dependency

### PR DESCRIPTION
**Pull request by WonderPanda**
Importing doesn't appear to be working, at least within a project built with the Angular CLI

### CODE REVIEW

**Comment by saiyaff** [comment]
@WonderPanda Did this solution work for you? I'm still having issues with implementing this with the angular version 2.1.0

**Comment by WonderPanda** [comment]
@msaiyaff It works for me, but I'm on version 2.3.1. Did you ensure that you installed medium editor through NPM before trying to do the require?

**Comment by jomarbarnobal** [comment]
angular cli says Cannot find module 'medium-editor'.)

**Comment by WonderPanda** [comment]
@jomarbarnobal Have you installed Medium Editor with NPM? It is a dependency in order for this to work

**Comment by kevcjones-archived** [comment]
The trick [for me] was i needed to install the types too 

`npm i --save @types/medium-editor`

i also had to include the css and javascript globally so that import found it correctly by editing the angular-cli.json, much like i had to with moment and jQuery.

```
"styles": [
        "../node_modules/semantic-ui-css/semantic.css",
	"styles.scss",
        "../node_modules/medium-editor/dist/css/medium-editor.min.css",
        "../node_modules/medium-editor/dist/css/themes/bootstrap.css"

      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/semantic-ui-daterangepicker/moment.min.js",
        "../node_modules/medium-editor/dist/js/medium-editor.min.js"
      ],`

**Comment by jomarbarnobal** [comment]
i manage to install this but the style not workin, ill try @KevCJones  sugestion

**Comment by jomarbarnobal** [comment]
this is the first i get when installing via npm 
screencapture-localhost-4200-1485329309790

**Comment by jomarbarnobal** [comment]
this is what i get when i use @KevCJones tips the css work but i got undefined and every time i type a text i have a blue line
Is the a problem or conflict in my css, I use materializecss
screencapture-localhost-4200-1485330238038

**Comment by codiak** [comment]
I'll give it a test in an Angular CLI project today. Sorry for the delay!

**Comment by saiyaff** [comment]
@codiak I have tried it with the Angular CLI and got it working. Thanks for it.
@KevCJones Installing @typings/... solved few issues I had. Thanks too.
How can I integrate the insert-plugin or any other plugins?
@WonderPanda @jomarbarnobal @KevCJones Help needed if you have done.

**Comment by codiak** [comment]
If anyone has suggestions on making import of the actual Medium Editor package _dead simple_, let me know. Otherwise, I'm going to close this as it seems import into Angular CLI projects is working fine.

**Pull request closed without merging**
